### ISSUE TITLE
Provide quote optionality for macro params

### ISSUE THREAD

**Issue by rlsalcido24** [rlsalcido24/lakehouse_utils#10]
the helper function by default wraps macro inputs in double quotes. This is fine for integers and column aliases-- however, for strings this will lead to conflicts if the inputs are already wrapped in double quotes. the 'workaround' is just to wrap the input in single quotes instead-- however it would be nice to automate this by adding a single/double quote param so that the logic will inject single quotes when user pattern is to double quote string inputs and vice versa (inject double quotes when user pattern is to single quote input).

**Comment by shabbirk-db** [comment]
Nice, interesting idea
